### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by qkren** [node-ffi-libraries/node-ffi-library-libusb-v1.0.23#1]
d:\test\ffi\node_modules\node-addon-api\napi-inl.h(416): error C3861: “napi_is_date”: 找不到标识符 (编译源文件 ..\src\ffi.cc) [D:\
test\ffi\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\test\ffi\node_modules\node-addon-api\napi-inl.h(711): error C3861: “napi_create_date”: 找不到标识符 (编译源文件 ..\src\ffi.cc)

**Comment by joelpurra** [comment]
The code in `node-ffi-library-libusb-v1.0.23` has unfortunately not yet been tested on Windows, only on Linux and macOS. Maybe there are problems on Windows that I do not know about, even if `libusb-1.0.dll` is included in this package.

```shell
npm install --save github:node-ffi-libraries/node-ffi-library-libusb-v1.0.23#semver:^1.0.0
```

- Can you run this command in an empty directory?
- Which other steps did you take?
- Can you provide more details about your system?
- Can you debug and see if you find a fix?

**Comment by qkren** [comment]
my os is win x86_64.
When I run the command:  npm install --save github:node-ffi-libraries/node-ffi-library-libusb-v1.0.23#semver:^1.0.0


`D:\test\ffi>npm install --save github:node-ffi-libraries/node-ffi-library-libusb-v1.0.23#semver:^1.0.0

> ref-napi@2.1.2 install D:\test\ffi\node_modules\ref-napi
> node-gyp-build


> ffi-napi@3.1.0 install D:\test\ffi\node_modules\ffi-napi
> node-gyp-build


D:\test\ffi\node_modules\ffi-napi>if not defined npm_config_node_gyp (node "D:\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  Building assembly file ..\..\..\deps\libffi\src\x86\win32.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win32.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> D:\test\ffi\node_modules\ffi-napi\build\Release\\libffi.lib
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> D:\test\ffi\node_modules\ffi-napi\build\Release\\nothing.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
d:\test\ffi\node_modules\node-addon-api\napi-inl.h(416): error C3861: “napi_is_date”: 找不到标识符 (编译源文件 ..\src\ffi.cc) [D:\
test\ffi\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\test\ffi\node_modules\node-addon-api\napi-inl.h(711): error C3861: “napi_create_date”: 找不到标识符 (编译源文件 ..\src\ffi.cc)
[D:\test\ffi\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\test\ffi\node_modules\node-addon-api\napi-inl.h(728): error C3861: “napi_get_date_value”: 找不到标识符 (编译源文件 ..\src\ffi.c
c) [D:\test\ffi\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\test\ffi\node_modules\ffi-napi\src\ffi.cc(11): error C3861: “napi_get_instance_data”: 找不到标识符 [D:\test\ffi\node_modul
es\ffi-napi\build\ffi_bindings.vcxproj]
d:\test\ffi\node_modules\ffi-napi\src\ffi.cc(347): error C3861: “napi_set_instance_data”: 找不到标识符 [D:\test\ffi\node_modu
les\ffi-napi\build\ffi_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\node\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "D:\\node\\node.exe" "D:\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\test\ffi\node_modules\ffi-napi
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ffi@1.0.0 No description
npm WARN ffi@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@3.1.0 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi-napi@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qkren\AppData\Roaming\npm-cache\_logs\2021-05-07T05_46_20_162Z-debug.log`

**Comment by joelpurra** [comment]
@qkren: thank you for the log output. It seems it's a problem in `ffi-napi`.

- https://github.com/node-ffi-napi/node-ffi-napi

```text
npm ERR! ffi-napi@3.1.0 install: node-gyp-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi-napi@3.1.0 install script.
```

Can you check here if you find a solution? Perhaps an upgrade to `ffi-napi` v4.0.3 (latest version) would help. Can you test if that works, and perhaps send a pull request to `ffi-packager`? It would help a lot since I am not using Windows.

- https://github.com/node-ffi-packager/node-ffi-packager

**Comment by qkren** [comment]
When I upgraded Node to 10.20.0, the install was successful
